
devMode: true

host: mq0
port: 1414
manager: QM1
channel: DEV.APP.SVRCONN
app: afsc.adapter
user: app
pass: 11111111

header: "rfh2"
#codedCharSetId: 1208
rootTag: tg
offRootTag: false

tls:
KeyRepository:
MaxMsgLength:

#browseQueue: DEV.QUEUE.2
#putQueue: DEV.QUEUE.1
#getQueue: DEV.QUEUE.2

multiQueues:
  - alias: first
    browse: DEV.QUEUE.2
    put: DEV.QUEUE.1
    get: DEV.QUEUE.2
  - alias: second
    browse: DEV.QUEUE.1
    put: DEV.QUEUE.2
    get: DEV.QUEUE.1
