devMode: false
logLev: DEBUG

host: mq1
port: 1414
manager: QMAPP1
channel: DEV.APP.SVRCONN
user: app
pass: 11
app:

tls: false
keyRepository: crypto/client/keys
maxMsgLength: 5000

header: prop # [prop|rfh2] значение по умолчанию - prop

rfh2OffRootTag: false
rfh2RootTag: usr

queues:
  # Первая пара очередей отправить | получить
  - alias: aliasQueueFooPut
    name: APP1.APP2.FOO.IN:put
#    name: SYS1.SYS2.FOO.IN:put
  - alias: aliasQueueFooGet
    name: APP2.APP1.FOO.OUT:get,browse

  # Вторая пара отправить | получить
  - alias: aliasQueueBarPut
    name: SYS1.SYS2.BAR.IN:put
  - alias: aliasQueueBarGet
    name: SYS2.SYS1.BAR.OUT:get,browse
