version: '3.7'

networks:
  pkg-mqpro-sample:
    external: true


x-deploy: &deploy-base
  replicas: 1
  restart_policy:
    condition: any


x-base: &base
  deploy: *deploy-base
  networks:
    - pkg-mqpro-sample


services:
#  sample:
#    <<: *base
#    image: pkg-mqpro-sample:1.0


  mq0:
    <<: *base
    image: ibmcom/mq:9.2.2.0-r1
    environment:
      - LICENSE=accept
      - MQ_ENABLE_METRICS=true
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=22
      - MQ_APP_PASSWORD=11
    #    web админпанель
    #    localhost:9443/ibmmq/console
    ports:
      - 9443:9443

