devMode: false
logLev: DEBUG

host: mq2
port: 1414
manager: QMAPP2
channel: DEV.APP.SVRCONN
user: app
pass: 11
app:

tls: true
keyRepository: /mqs/mq-ams
maxMsgLength: 5000

header: rfh2

rfh2OffRootTag: false

queues:
  # Первая пара очередей отправить | получить
  - alias: aliasQueueFooPut
    name: APP2.APP1.FOO.RQ:put
  - alias: aliasQueueFooGet
    name: APP1.APP2.FOO.Q:get,browse

  # Вторая пара отправить | получить
pipes:
  - alias: aliasQueueBar
    put: APP2.APP1.FOO.RQ
    get: APP1.APP2.FOO.Q
