devMode: true
logLev: DEBUG

host: mq1
port: 1414
manager: QMAPP1
channel: DEV.APP.SVRCONN
user: app
pass: 11
app:

tls: true
keyRepository: /mqs/mq-ams
maxMsgLength: 5000

header: rfh2 # [prop|rfh2] значение по умолчанию - prop

rfh2OffRootTag: false
#rfh2RootTag: usr # по умолчанию <usr>

# Данные очередей
queues:
  # Первая пара очередей отправить | получить
  - alias: aliasQueueFooPut
    name: APP1.APP2.FOO.RQ:put
  - alias: aliasQueueFooGet
    name: APP2.APP1.FOO.Q:get,browse

# Абстракция над очередями, создающая двух направленный канал
channels:
  - alias: aliasQueueBar
    put: BHVE.IIB.GET_PAYMENT.REQ.RQ
    get: IIB.BHVE.GET_PAYMENT.RES.Q
