devMode: false
logLev: DEBUG

host: mq1
port: 1414
manager: QMAPP1
channel: DEV.APP.SVRCONN
user: app
pass: 11
app:

tls: true
keyRepository: /mqs/mq-ams
maxMsgLength: 5000

header: rfh2

rfh2OffRootTag: false

queues:
  - alias: aliasQueueFooPut
    name: APP1.APP2.FOO.RQ:put
  - alias: aliasQueueFooGet
    name: APP2.APP1.FOO.Q:get,browse

pipes:
  - alias: aliasQueueBar
    put: APP1.APP2.FOO.RQ
    get: APP2.APP1.FOO.Q
